# Generated by Django 4.2.3 on 2023-08-17 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='marca_auto',
            new_name='Marca',
        ),
    ]
